server:
  port: 9901

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/223_projekt
    username: root
    password:
  jpa:
    show-sql: true

keycloak:
  auth-server-url: http://localhost:9902/auth
  realm: 223
  bearer-only: true
  resource: 223-backend
  cors: true
  principal-attribute: preferred_username
